CREATE TABLE IF NOT EXISTS ink_prices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  model_name VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  price_sis DECIMAL(10, 2) DEFAULT NULL,
  price_vst DECIMAL(10, 2) DEFAULT NULL,
  price_synnex DECIMAL(10, 2) DEFAULT NULL,
  price_bcom DECIMAL(10, 2) DEFAULT NULL,
  price_metro DECIMAL(10, 2) DEFAULT NULL,
  price_advice DECIMAL(10, 2) DEFAULT NULL,
  price_svoa DECIMAL(10, 2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
